### ISSUE TITLE
ctrol as toggle key

### ISSUE THREAD

**Issue by jcvillaquira** [FreeFem/FreeFem-website#1]
The new functionality that allows toggling between documentation and examples is awesome.
However, using the Ctrol key is not ideal since it is used a lot in shortcuts, so it is really messy to look up things (Ctrol + f), move around between tabs (Ctrol + tab), etc.

Is there any way that another key can be chosen? Or maybe no key and a switch instead of a checkbox . . . It would be awesome.

Let me know if there is something I can contribute to.

**Comment by sgarnotel** [comment]
Switched to Alt key

Thank you for your feedback
